name: apkmirror2fdroid
version: 0.1.0
summary: Mirror packages from apkmirror.com to your F-Droid Repo
description: Mirror packages from apkmirror.com to your F-Droid Repo
confinement: strict
grade: stable

apps:
  apkmirror2fdroid:
    command: apkmirror2fdroid
    plugs: [network, network-bind]

parts:
  apkmirror2fdroid:
    plugin: nodejs
    node-engine: 10.10.0
    source: .
    override-build: |
      - npm i
      - npm run prepublishOnly
      - snapcraftctl build
    stage-packages:
      - fdroidserver
      - libdb5.3
    prime:
      - -usr/lib/jvm/java-8-openjdk-*/jre/lib/security/cacerts
